version: '3'

services:

  mongodb:
    build: ./mongodb
    container_name: list_mongodb
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=${MONGODB_ADMIN_USER}
      - MONGODB_ADMIN_PASS=${MONGODB_ADMIN_PASS}
      - MONGODB_APPLICATION_DATABASE=${MONGODB_APPLICATION_DATABASE}
      - MONGODB_APPLICATION_USER=${MONGODB_APPLICATION_USER}
      - MONGODB_APPLICATION_PASS=${MONGODB_APPLICATION_PASS}
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/db/log
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017

  app:
    build: ./list
    container_name: list_app
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB=mongodb://${MONGODB_APPLICATION_USER}:${MONGODB_APPLICATION_PASS}@mongodb/${MONGODB_APPLICATION_DATABASE}
      - DOMAIN=http://localhost:3000
      - POSTMARK_FROM=${POSTMARK_FROM}
      - POSTMARK_KEY=${POSTMARK_KEY}
    ports:
      - "3000:3000"
    command: node node_modules/.bin/micro

volumes:
  mongodb:
